name: Generate Diagrams

on: [push]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Install Dependencies
      run: |
        sudo apt-get install -y graphviz
        python -m pip install --upgrade pip
        pip install -r src/diagrams/requirements.txt

    - name: Generate diagrams 1-2-3
      run: |
        python src/diagrams/main1.py
        python src/diagrams/main2.py
        python src/diagrams/main3.py

    - name: Commit and Push Diagrams
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add docs/diagrams/*
        git commit -m "Auto-update diagrams"
        git push
